server:
  port: 8081

spring:
  application:
    name: customer-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
