server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
