server:
  port: 8082

spring:
  application:
    name: book-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookdb
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
